JD_SYSTEM='''You are a precise job-description information extraction system. Extract ONLY information supported by the supplied JD. Do not use a predefined keyword list. Do not invent technologies. Return valid JSON only.'''
RESUME_SYSTEM='''You are a precise resume information extraction system. Extract ONLY information supported by the resume evidence. Never invent skills, experience, projects, education or certifications. Return valid JSON only.'''
ATS_SYSTEM='''You are an expert ATS resume analysis system. Never invent candidate information. Use retrieved evidence and extracted profiles. Distinguish exact, semantic, partial and missing. Do not encourage false claims. Return valid JSON only.'''

def jd_prompt(jd, context):
    return f'''Extract the important requirements from this actual job description.\n\nJD:\n{jd}\n\nRetrieved JD evidence:\n{context}\n\nReturn exactly this JSON shape:\n{{"job_title":"","required_skills":[],"preferred_skills":[],"programming_languages":[],"frameworks_and_libraries":[],"tools_and_platforms":[],"databases":[],"cloud_and_devops":[],"ai_ml_skills":[],"data_skills":[],"soft_skills":[],"education_requirements":[],"experience_requirements":[],"certifications":[],"important_general_keywords":[]}}'''

def resume_prompt(resume_context):
    return f'''Extract the candidate profile using ONLY this resume evidence.\n\nEvidence:\n{resume_context}\n\nReturn exactly:\n{{"programming_languages":[],"frameworks_and_libraries":[],"tools_and_platforms":[],"databases":[],"cloud_and_devops":[],"ai_ml_skills":[],"data_skills":[],"soft_skills":[],"projects":[],"experience":[],"education":[],"certifications":[],"important_keywords":[]}}'''

def ats_prompt(jd_profile,resume_profile,matching,jd_context,resume_context):
    return f'''Analyze the resume against the job description using only the supplied evidence.\n\nJD PROFILE:\n{jd_profile}\n\nRESUME PROFILE:\n{resume_profile}\n\nSEMANTIC MATCHING BASELINE:\n{matching}\n\nJD EVIDENCE:\n{jd_context}\n\nRESUME EVIDENCE:\n{resume_context}\n\nReturn exactly:\n{{"overall_summary":"","matched_skills":[{{"skill":"","match_type":"exact|semantic","resume_evidence":"","reason":""}}],"partial_matches":[{{"jd_requirement":"","candidate_evidence":"","gap":""}}],"missing_skills":[{{"skill":"","importance":"high|medium|low","reason":""}}],"jd_keywords":[],"resume_keywords":[],"missing_keywords":[],"experience_analysis":"","education_analysis":"","project_relevance":[{{"project":"","relevance":"high|medium|low","reason":""}}],"ats_issues":[],"recommendations":[]}}'''

def tailor_prompt(template, jd_profile, resume_profile, analysis):
    return f'''You are a resume tailoring engine. Rewrite the candidate's resume content to better align with the JD while preserving every factual constraint.\n\nSTRICT RULES: Never fabricate skills, technologies, work experience, internships, projects, certifications, degrees, grades, achievements, job titles, years, responsibilities or tools. You may rewrite wording, reorder content, emphasize truthful existing technologies, improve the summary, and use JD terminology only where supported by the resume. If a requirement is missing, do not add it. Preserve the supplied LaTeX design and produce complete compilable LaTeX.\n\nJD PROFILE:\n{jd_profile}\n\nRESUME PROFILE:\n{resume_profile}\n\nRAG ANALYSIS:\n{analysis}\n\nREFERENCE LATEX TEMPLATE:\n{template}\n\nReturn only the complete LaTeX document, beginning with \\documentclass and ending with \\end{{document}}.'''
